kernelwernel/VMAware

src/vmaware.hpp

Fix for compilation issue/MSVC (Windows)

Fix for compilation issue/MSVC

---

src/vmaware.hpp

So this is a WIP (a demonstration of idea that I was talking about)
it's not complete, just an example how it might be done
if you like it I could continue clean up

__VMAWARE_DEBUG__ refactoring PoC

---

src/cli.cpp

Windows does not use terminal ANSI escape sequences. If you want to change font color, there is special API function call for it. Or, since Windows 10 version 16257, you can use ANSI escape sequences. But, for backwards compatibility, you need to enable it in each application by using the SetConsoleMode API function call. Or enable it for all applications by changing global Windows settings (in registry). So, in this pull request I added the SetConsoleMode call.

win_ansi_enabler

---

src/cli.cpp
src/vmaware.hpp

just all the compiler warnings fixes that I showed you yesterday, they do not change the functionality of any vm detection

MSVC warning fixes

---

.github/workflows/build_run_win_32.bat
.github/workflows/build_run_win_64.bat
.github/workflows/windows.yml

upload exe

---

.all-contributorsrc
README.md
docs/documentation.md
src/vmaware.hpp

Reverts kernelwernel/VMAware#70

Revert "changes to contributors"

---

docs/documentation.md
src/vmaware.hpp
src/vmaware_MIT.hpp

As discussed here https://github.com/kernelwernel/VMAware/pull/130#issuecomment-2303088220 :)

Add VM::SPOOFABLE to VM::ALL

---

src/cli.cpp
src/vmaware.hpp

Removed two Hyper-V RAW detection based techniques
Improved speed of registry checking by working now with ASCII strings
Initialized variables in WMI Wrappers
Explanation comments for execution of privileged CPU instructions in a user-mode library

Removed Hyper-V RAW string detection based techniques

---

TODO.md
src/vmaware.hpp

Added ACPI data technique into Hyper-X

Added ACPI technique

---

TODO.md
auxiliary/updater.py
src/cli.cpp
src/vmaware.hpp
src/vmaware_MIT.hpp

- Added technique based on scanning the AcpiData value in windows machines for known vm brand strings.
- Added technique based on detecting known HDD serial numbers used on virtual machines.
- Added technique based on fetching Interruptor Descriptor Table base addresses to detect known remapping ranges used by virtual machines such as VirtualBox, while handling multiple CPU core issues.
- Added technique based on detecting known kernel drivers used by virtual machines.

Added 4 new techniques

---

src/cli.cpp
src/vmaware.hpp

```cpp
[[nodiscard]] static bool port_connectors() {
if (!wmi::initialize()) {
return false;
}
std::vector<wmi::result> results = wmi::execute(L"SELECT * FROM Win32_PortConnector", { L"Caption" });
wmi::cleanup();
return results.empty();
}
```

Added connection ports technique

---

README.md
src/vmaware.hpp

fixed readme

---

CMakeLists.txt
README.md
TODO.md
docs/documentation.md
src/cli.cpp
src/vmaware.hpp
src/vmaware_MIT.hpp

Dev (hi nakata, with rizz)

---

src/cli.cpp
src/vmaware.hpp

Added GetFunctionAddresses utility
Removed uptime technique
Fixed driver_names technique, improved speed
Fixed explanation in IDT GDT mismatch technique
Changed capitalization in some outputs of the CLI
Changed score of IDT GDT mismatch to 50
Changed score of driver_names to 80

removed uptime technique, fixed driver_names technique

---

src/vmaware.hpp

- added more methods to detect thread tampering
- added code documentation for the technique
- removed hyper-threading check
- changed score from 60 to 50

improved intel_thread_count_mismatch

---

README.md
docs/documentation.md
src/cli.cpp
src/vmaware.hpp

Removed vpc_proc, as we were checking the process names of it in the vm_proc technique already
Removed vmware_registry, as we were checking for its key in vm_registry already
Removed vbox_window_class, as its effectiveness depends on vm_processes
Removed valid_msr, as it can't run in usermode
Removed user_check due to VMware not having that default Windows username on any of its products
Removed hyperv_event_logs, as it was already being checked in hyper_x, and now hyper_x will run always
Made sidt5 technique compatible with both 32 and 64 bits
Modified  vm_files function to work only with 1 byte strings, improcing speed
Modified vm_files function to get the Windows path dynamically instead of harcoding it to C:\Windows (which is not always the case)
Modified vm_processes to use …

2.1 version

---

docs/documentation.md
src/cli.cpp
src/vmaware.hpp

Added HvlQueryDetailInfo technique
Improved Registry scanner
Changed score of virtual_processors to 50
Changed score of motherboard_product to 50

Added HvlQueryDetailInfo technique

---

src/vmaware.hpp

- Improved comments in util struct
- Added needed sanity checks in IDT_GDT_MISMATCH, VIRTUAL_PROCESSORS and VM_SIDT techniques
- Added new utility function to check if hypervisor cpuid specific leaves are present

Added sanity checks in some techniques

---

docs/documentation.md
src/cli.cpp
src/vmaware.hpp
src/vmaware_MIT.hpp

i hate python i hate python i hate python i hate python i hate python i hate python i hate python i hate python i hate python i hate python

virtual disk detection and kernel pool detection

---

docs/documentation.md
src/cli.cpp
src/vmaware.hpp
src/vmaware_MIT.hpp

updated docs and removed 2 inexistent techniques

updated docs

---

TODO.md
src/vmaware.hpp

Improved speed of qemu_USB
Fixed diagnostic policy service search
Updated TODO

Improved speed of qemu_USB

---

README.md
TODO.md
src/vmaware.hpp
src/vmaware_MIT.hpp

Fixed vmid and vmid_0x4 techniques
Updated TODO

Fixed vmid and vmid_0x4 techniques

---

README.md
docs/documentation.md
src/vmaware.hpp

added Qihoo 360 Sandbox and additional checks for CUCKOO and QEMU

added Qihoo 360 Sandbox

---

docs/documentation.md
src/cli.cpp
src/vmaware.hpp

added unknown_manufacturer technique
improved wmi wrapper
improved vm_memory
improved wmi_temperature
moved check_audio to MIT as it's not a GPL technique, the code was taken from InviZzzible project (GPL) which took it from Joe's 360 Sandbox Security (MIT)

added unknown_manufacturer technique

---

docs/documentation.md
src/cli.cpp
src/vmaware.hpp

Fixed port_connectors's return
Added xgetbv call for x86

Fixed port_connectors and added OSXSAVE technique

---

docs/documentation.md
src/cli.cpp
src/vmaware.hpp

Removed VM::SENSORS as it's unreliable
Made VM::OSXSAVE compatible with x64 too

Removed VM::SENSORS

---

docs/documentation.md
src/cli.cpp
src/vmaware.hpp

improved our garbage ass shit trashy rdtsc check

improved detectrions for timing anomalies

---

README.md
docs/documentation.md
src/README.md
src/cli.cpp
src/vmaware.hpp
src/vmaware_MIT.hpp

> Removed Eventlog, WMI and COM related headers and linking
> Improved performance and spoofing resistance of VM::AUDIO
> Integrated VM::HARDENER_LOADER into VM::FIRMWARE with a faster scanning algorithm
> Fixed compatibility with C++ 11
> Made nsjail_proc_id a Linux only technique, it was being compiled for all platforms, and added missing @implements comment

fixed C++ 14 compatibility

---

README.md
TODO.md
auxiliary/benchmark.cpp
docs/documentation.md
src/README.md
src/cli.cpp
src/vmaware.hpp
src/vmaware_MIT.hpp

Improved QEMU+KVM+HYPERV detections
Improved support for MSVC+Clang compilation
Improved detections of Hyper-V virtual GPUs

Added new Hyper-X state: HYPERV_ENLIGHTENMENT

---

docs/documentation.md
src/cli.cpp
src/vmaware.hpp

Improved VM::PROCESSOR_ID
Improved VM::GPU

detection improvements

---

docs/documentation.md
src/vmaware.hpp
src/vmaware_MIT.hpp

- updated intel_thread_mismatch
- updated documentation

updated core database

---

auxiliary/add_technique.py
docs/documentation.md
src/cli.cpp
src/vmaware.hpp

PCI technique

---

src/cli.cpp
src/vmaware.hpp
src/vmaware_MIT.hpp

updated header dates and release in source

---

src/vmaware.hpp
src/vmaware_MIT.hpp

Added SEH handler in VM::TIMER
Replaced _stricmp with strcmp on virtualbox shared folders check
Removed compilation of VM::AMD_SEV for Windows
Removed Hyper-V duplicates on VM type map

updated VM::TIMER

---

.github/workflows/cmake-multi-platform.yml
README.md
src/README.md
src/cli.cpp
src/vmaware.hpp
src/vmaware_MIT.hpp

Improved Hyper-X's virtual trust level checks
Improved QPC and TSC sync checks in VM::TIMER

Major changes to Hyper-X mechanism

---

README.md
docs/documentation.md
src/cli.cpp
src/vmaware.hpp
src/vmaware_MIT.hpp

Added checks for more ACPI table strings

Merged dmfrpro's pull request 

---

src/cli.cpp
src/vmaware.hpp
src/vmaware_MIT.hpp

2.1.2 update

---

src/vmaware.hpp
src/vmaware_MIT.hpp

This PR adds QEMU & Xen PCI Vendor ID checks for Windows registry technique

Add checks for PCI registry keys for KVM & Xen

---

src/vmaware.hpp
src/vmaware_MIT.hpp

Add more strict firmware scan & registry checks

---

src/vmaware.hpp
src/vmaware_MIT.hpp

This PR adds checks for IddSampleDriver and VirtualDisplayDriver which are used in conjunction with looking-glass

Add Virtual Display Driver detection

---

src/vmaware.hpp
src/vmaware_MIT.hpp

Fix typo in registry checks

---

src/vmaware.hpp
src/vmaware_MIT.hpp

Improved execution speed on TIMER, VM_PROCESSES, VIRTUALBOX_SHARED_FOLDERS and MAC_ADDRESS_CHECK

Addressed critical performance bottlenecks

---

docs/documentation.md
src/cli.cpp
src/vmaware.hpp
src/vmaware_MIT.hpp

Reverts kernelwernel/VMAware#340

Revert "Refactoring & Looking Glass detection"

---

src/vmaware.hpp

Added checks for SSDT tables
Added comments explaining the behavior of the new trap technique

SSDT firmware heuristics

---

docs/documentation.md
src/cli.cpp
src/vmaware.hpp

[+] Improved binary translation layer detection
[+] Improved timing detections
[+] Improved detections for Hyper-V VMs
[+] New detection for vm-related global device objects
[/] Removed PCI, USB and HDAUDIO checks from PCI_DEVICES in the case of Hyper-V VMs

dramatically increased AML parsing speed

---

docs/documentation.md
src/cli.cpp
src/vmaware.hpp

also removed DISK_SIZE technique

improved wine, timing, binary translation and firmware checks
