src/vmaware.hpp
The code was modified to handle wide character strings instead of narrow character strings using MultiByteToWideChar. The original code used narrow character strings (LPCSTR or const char*) that were causing compilation issues on MSVC VS 2022
The code was also compiled and tested after the changes to ensure the modifications are ok
> 1. Compilation errors in the original code:
> 2. Compilation status in the modified code:
=> Fixed some MSVC errors

src/vmaware.hpp
Fixed every compiler warning for all c++ versions on windows systems (not really necessary tho, the library is quite well-made)
'dll' could be '0':  this does not adhere to the specification for the function 'strcmp'. vmaware.hpp - 3410
'szBuff' could be '0':  this does not adhere to the specification for the function 'strcmp'. vmaware.hpp - 3045
VARIANT '&vtProp' was provided as an _In_ or _InOut_ parameter but was not initialized (expression 'vtProp').	vmaware.hpp - 3626
=> Fixed every MSVC warning

src/vmaware.hpp
> Fixed in the FIRST COMMIT
To see all the changes made in the first commit, you should click on "Ignore whitespaces", like this:
Link: https://github.com/NotRequiem/VMAware/commit/600d8b79f6be5f8f90382adf5ee4981631a0dfd7?diff=unified&w=1
Fixed some IntelliSense warnings about buffer overruns, variants not being initialized with VariantInit and 'dll could be 0'.
> Fixed in the SECOND COMMIT
Normally in large source files, when fixing errors in a source file using Visual Studio, you may find no errors when you finish. But if you copy and paste the same source code with the same compiler flags in other project, using Visual Studio, more errors/warnings may be shown. Example of pasting the same code in another project:
So, if you constantly fix errors and warnings until you find no errors in …
=> Fixing code for MSVC

src/vmaware.hpp
This fixes the following warnings and compiler errors in VS2022 and VSCode.
`error C2131: expression did not evaluate to a constant` `expression must have a constant value C/C++(28)`
=> fix constant value error for vm_files_extra

src/vmaware.hpp
- Fixed string function returning nullptr instead of empty strings when handling failure
- Initialized core class variables to avoid ISO standard warnings
- Modified the usage of const_cast to _T
```cpp
const struct map_key {
LPCTSTR KeyPath;
LPCTSTR ValueName;
} ResourceRegistryKeys[ResourceRegistryKeysLength] = {
{
const_cast<LPTSTR>("Hardware\\ResourceMap\\System Resources\\Physical Memory"),
const_cast<LPTSTR>(".Translated")
_T("Hardware\\ResourceMap\\System Resources\\Physical Memory"),
_T(".Translated")
},
{
const_cast<LPTSTR>("Hardware\\ResourceMap\\System Resources\\Reserved"),
const_cast<LPTSTR>(".Translated")
_T("Hardware\\ResourceMap\\System Resources\\Reserved"),
_T(".Translated")
},
{
const_cast<LPTSTR>("Hardware\\ResourceMap\\System Resources\\Loader Reserved"), …
```
=> Fixed compilation errors for projects with unicode settings enabled

README.md, src/vmaware.hpp, src/vmaware_MIT.hpp
Hi there!
Thank you for this awesome project. To make it better, I made some bug fixes:
- `VM::ALL` missed `RDTSC` and `RDTSC_VMEXIT` techniques, so I've added them;
- `flag_to_string` function missed a lot of new techniques, so I've appended them;
- Some functions used `cout <<` instead of `debug(...)`, so now they use `debug(...)`.
I hope, 2 first fixes are easy to understand, but the last one needs some explanation: actually, in your lib `debug()` and `core_debug()` macroses can be replaced with end-user's debugging library, so if you use `cout`, it won't work.
Also I have a question about `VM::ALL` - maybe it also must enable `VM::SPOOFABLE` flag, because without it not all techniques are executed?
=> Fix VM::ALL, add missing techniques to flag_to_string and replace COUTs with debug(...)

src/vmaware.hpp
**Warning**
```
Warning	C4244	'initializing': conversion from '_Ty' to '_Ty2', possible loss of data
with
[
_Ty=int
]
and
[
_Ty2=VM::u8
]	C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include\utility	247
```
**Explanation**
The warning suggests that converting between these types (i.e., from DWORD to u8) may cause data loss since DWORD is 32-bit and u8 is only 8-bit. 
**Solution**
All the values you're assigning to the u8 type are valid and will fit within uint8_t. Therefore, casting them as static_cast<u8> will work fine to supress the MSVC compiler warning without any data loss:
- The first value, 6, is well within the range of uint8_t (0-255).
- The rest of the values (7, 8, 10, 11) also fit within the valid range of uint8_t.
By explictly casting the …
=> stupid change to avoid compiler warning

README.md, src/cli.cpp, src/vmaware.hpp
**New detection method**
Using wmic to get the chip type (gpu_chiptype), detects Hyper-V, Virtualbox and VMware for now. Haven't tested for QEMU yet.
=> add gpu_chiptype detection method

docs/documentation.md, src/cli.cpp, src/vmaware.hpp
- Returns true if a tamper attempt in the number of threads present in the system is detected
- Modified request access needed to detect if a process is running to PROCESS_QUERY_LIMITED_INFORMATION instead of PROCESS_QUERY_INFORMATION
- Removed debug output in GetThreadsUsingWMI for production builds
=> Added new techniques

docs/documentation.md, src/cli.cpp, src/vmaware.hpp, src/vmaware_MIT.hpp
Added motherboard_product technique to replace old motherboard techniques (25 of score)
Added VIRTUAL_PROCESSORS to the Windows list technique
Added compatibility for x64 bits to the virtual_processors technique
Reduced physical port connectors score to 10 as previously discussed
Removed VPC_board and hyperv_board technique, they are not reliable because Microsoft motherboard exists
Fixed Hyper-X detecting Microsoft motherboards as Hyper-V VMs
Fixed Physical port connectors technique from flagging Surface Pro devices
Fixed GetThreadsUsingWMI returning an incorrect value in case of failure
Fixed audio_devices using a different WMI threading mode than the rest of techniques
Improved WMI wrapper to handle multiple WMI initialization modes, previously it was returning an error if WMI was …
=> Hyper-X fix

docs/documentation.md, src/cli.cpp, src/vmaware.hpp, src/vmaware_MIT.hpp
- Fixed 237 compiler warnings related to type safety
- Fixed registry debugs (function accessing invalid registry keys)
- Fixed is_smbios_hyperv function (this functions has been not working properly since months ago lol)
- Fixed is_acpi_hyperv function (same as above, the problema was trying to Access the registry with KEY_ALL_ACCESS instead of KEY_READ
- Fixed 3 hypervisor detection techniques flagging inconsistencies because the lack of a condition to check if hypervisor CPUID specific leaves are present on the system:
`VM_SIDT, VIRTUAL_PROCESSORS and IDT_GDT_MISMATCH`
- Fixed nettitude_vm_memory, has never been working, it was always failing when trying to get the buffer to scan the memory maps
-------------------------------------------------------------------------------------------- …
=> major update and important fixes

docs/documentation.md, src/cli.cpp, src/vmaware.hpp
Increased MSSMBIOS score from 75 to 85, to have the same score as ACPI (they get the vm strings from almost the same source)
Increased  PROCESSOR_NUMBER from 25 to 50, a CPU should not have less than 4 threads nowadays
**------------------------------------------------------------------------------------------------------------------------------**
Added more detections for VMWare in vm_sidt technique
Added more detections for several VM brands in ACPI technique
Added brand return in gpu names technique, this means that now it will not return true but return the specific brand detected
**------------------------------------------------------------------------------------------------------------------------------**
Made AMD_SEV technique compatible with Linux and MacOS only …
=> hyper-v and amd_sev fix

README.md, docs/documentation.md, src/vmaware.hpp, src/vmaware_MIT.hpp
Updated vmaware MIT version
Updated README
Updated numbers of sections in both vmaware headers
Added Google Compute Engine detections through WMI
=> Added GCE detections

src/vmaware.hpp
When compiling the Windows Unicode version, calling the ANSI version of SetupDiGetDeviceRegistryPropertyA returns a string with an incorrect format.
=> Fix SETUPDI diskdrive checking with Windows UNICODE build

README.md, docs/documentation.md, src/cli.cpp, src/vmaware.hpp
- VM::AUDIO -> now it only verifies the working audio pipeline. This code reduces API calls from ~15 in original code to 3 critical ones, which is 10-15x faster execution time compared to DirectShow approach and avoids unnecessary filter creation/cleanup
- VM::VIRTUAL_REGISTRY -> Removed used of RtlEqualUnicodeString API
- VM::BAD_POOLS -> Precomputed tags so that each literal now represents the four-character pool tag in little‑endian order
- VM::PROCESSOR_ID -> Replaced WMI query with direct memory read from SMBIOS firmware data
- VM::WMI_TEMPERATURE -> Replaced WMI query with more lightweight API (SetupDiGetClassDevs), bypassing also the need of admin privileges
- VM::WMI_MANUFACTURER -> Removed, as after reverse engineering, I noticed that this WMI query takes the data from SMBIOS, …
=> The Optimization Update

TODO.md, src/vmaware.hpp
Updated TODO.md
VM::MEMORY -> Implemented a trie with failure links for efficient multipattern search using the Aho-Corasick algorithm, reducing the buffer processing to a single pass. The technique will also skip memory regions and buffers too small to contain any pattern to reduce unnecesary reads. std::optional was replaced with const char*& result so that suitable conversions when returning false or true in the function can be found by compilers (especially Clang)
util::SetDebugPrivilege -> modified so that it can also disable debugging privileges for the current process. VMAware will now check if the token was already enabled by the program using our lib to determine if the debug privilege should be modified
=> updated VM::VM_MEMORY

docs/documentation.md, src/vmaware.hpp
The score was modified to 95, so that at least 1-2 more techniques must be flagged to conclude that the system is running on a VM
The mechanism to detect thread and cpu data tampering by cross-referencing was removed until I confirm it actually works against hardeners, likely not
People can disable logical or physical cores because/to:
1. Redistribute power/thermal headroom to achieve higher clock speeds on fewer cores. When overclocking, having fewer active cores could allow higher clock speeds on the remaining cores since the power and thermal headroom is redistributed. Enthusiasts might do this to push performance on specific cores for tasks that don't need many cores but benefit from higher clock speeds.
2. Prioritize performance for tasks (e.g., legacy software, older games) that …
=> Changed scores in thread mismatch techniques to 95

README.md, docs/documentation.md, src/README.md, src/cli.cpp, src/vmaware.hpp
> added detections for QEMU Hyper-V Enlightenments in Hyper-X mechanism
> improved util::vmid_template, same as the previous functions but now the if statements are rearranged so that known brands are checked first to return faster, and the technique_name is not passed as a parameter anymore (its calculated at compile-time if debug builds are enabled for performance benefits)
> improved util::cpu_manufacturer, it wont generate all the permutations, it will generate only the correct permutation depending on the leaf for better performance
> improved VM::VMID, it will check for new leafs now
> Merged VM::VMID_0x4 into VM::VMID for better readability (and a 'jmp' instruction less when compiling heh)
=> added detections for Hyper-V Enlightenments

docs/documentation.md, src/vmaware.hpp
- Improved debug output in all windows functions
- Minimized risk of false flagging in VM::TIMER
- Improved VM_FILES to handle Vbox and VMware separately
=> Improved debug analysis

docs/documentation.md, src/cli.cpp, src/vmaware.hpp
+ added virtual detections in two more SCSI ports
=> fixed critical issues

src/cli.cpp, src/vmaware.hpp, src/vmaware_MIT.hpp
Make sure that the library compiles on Windows when WIN32_LEAN_AND_MEAN is defined.
- Added missing winioctl.h for STORAGE_PROPERTY_QUERY and IOCTL_STORAGE_PROPERTY_QUERY
- CLI now compiles with with WIN32_LEAN_AND_MEAN to make sure this won't break in the future
=> Make sure that the library compiles on Windows when WIN32_LEAN_AND_MEAN is defined

src/vmaware.hpp, src/vmaware_MIT.hpp
Added ifndef to avoid compilation issue if symbol was already defined before
We compile using /D WIN32_LEAN_AND_MEAN
Otherwise we get:
```
error C2220: the following warning is treated as an error
warning C4005: 'WIN32_LEAN_AND_MEAN': macro redefinition
message : 'WIN32_LEAN_AND_MEAN' previously declared on the command line
```
=> Added ifndef to avoid compilation issue if symbol was already defined before

docs/documentation.md, src/vmaware.hpp, src/vmaware_MIT.hpp
VM::TIMER
- Added lambda to increase and restore thread priority for Windows, MacOS and Linux
- Added better heuristics for failing a check (now you must trigger at least 50% iterations)
- Re-organized the code with better code clarity, more debug output and early exit returns
VM::GPU_CAPABILITIES
- Added debug output when a check that it's not based on VID and PID is triggered
VM::DEVICES
- Increased score from 45 to 50
=> Improvements to VM::TIMER

README.md, docs/documentation.md, src/README.md, src/cli.cpp, src/vmaware.hpp, src/vmaware_MIT.hpp
removed VM::IDT_GDT_SCAN, as kernel leak address prevention for IDT base addresses seems to be only present on Hyper-V, which we were skipping as to not flag normal Windows machines
added the threshold variable in all debug outputs of VM::TIMER
improved speed of physical core count checks
=> removed VM::IDT_GDT_SCAN

README.md, auxiliary/benchmark.cpp, docs/documentation.md, src/README.md, src/cli.cpp, src/vmaware.hpp, src/vmaware_MIT.hpp
The CIM string that we can get from Win32_Processor is not the same value as the one extracted from the SMBIOS table, it comes from CPUID with function 1
The 32‐bit value from EDX -> features and initial signature parts
The 32‐bit value from EAX -> family, model, and stepping 
For example, the CIM string in one of my machines after running wbemtest on root\cimv2 is 'BFEBFBFF000A0655' (EDX = 0xBFEBFBFF and EAX = 0x000A0655)
```cpp
#include <iostream>
#include <intrin.h>
#include <iomanip>
#include <sstream>
#include <string>
std::string GetProcessorId() {
int cpuInfo[4] = {0};
__cpuid(cpuInfo, 1);
// EDX (first) and EAX (second) as 8-hex-digit parts
std::ostringstream oss;
oss << std::hex << std::setw(8) << std::setfill('0') << cpuInfo[3] // EDX
<< std::setw(8) << std::setfill('0') << …
```
=> removed VM::PROCESSOR_ID

docs/documentation.md, src/cli.cpp, src/vmaware.hpp, src/vmaware_MIT.hpp
This PR does:
1. Merge QEMU_GA into VM_PROCESSES & refactoring (code style is similar to GPU VM strings method), legacy util method `get_running_process_names()` removed. VM_PROCESSES became more verbose in debug mode
2. Add `looking-glass-host.exe` & `VDDSysTray.exe` processes checks (VDDSysTray is a companion app for VirtualDisplayDriver, which is commonly used in conjunction with looking-glass)
Tested on Windows 11 VM, needs testing on Linux
=> Refactoring & Looking Glass detection

README.md, docs/documentation.md, src/README.md, src/cli.cpp, src/vmaware.hpp, src/vmaware_MIT.hpp
- Made constant enumeration of supported platforms in the documentation of each technique. For example, instead of typing "Windows, Linux" in some places and "Linux and Windows" in some others, it's now "Linux and Windows" on all places 
------------
- Merged VM::OFFSEC_SIDT and VM::VPC_SIDT into VM::SIDT
- Merged VM::OFFSEC_SGDT into VM::SGDT
- Merged VM::OFFSEC_SLDT into VM::SLDT
- Made VM::SIDT and VM::SGDT fully compatible with x64 and Clang/GCC/MSVC
------------
- Rewrote CODE DOCUMENTATION section at the beggining of the library to fix some small grammatical mistakes
- Rewrote category sections of some techniques to specify that they are only compatible with x86_32 rather than x86
------------
- Improved speed of VM::GPU_CAPABILITIES
- Improved speed of VM::GPU_NAMES
------------
- …
=> Major changes

src/vmaware.hpp, src/vmaware_MIT.hpp
This small PR adds QEMU fw_cfg device detection via ACPI tables scan & also fixes incorrect targets. fw_cfg device is crucial for he boot process
=> Add QEMU fw_cfg to ACPI scan & fix typos in FIRMWARE_SCAN

auxiliary/benchmark.cpp, src/vmaware.hpp
re-ordered optimization directives
removed some stupid unused variable
cross-platform ASCII escapes for benchmarking
=> clang pragma re-ordering

docs/documentation.md, src/vmaware.hpp
<br>
* Fixed a compilation error during macOS builds caused by a missing comma at the end of the #if(APPLE) block, specifically in the final std::make_pair line.
* Also added missing CPUID-related headers to resolve a build error when building for x86 on ARM-based macOS.
=> Fix macos build error

docs/documentation.md, src/vmaware.hpp
"If the host CPU supports split lock detection and VM guests perform misaligned atomic memory access, the host Linux kernel may artificially slow down the virtual CPUs of the guests as part of the split lock mitigation. For the VM, this looks like a virtual CPU core freezes for several milliseconds every time a misaligned atomic memory access is performed. In the case of Windows VMs, in-guest latency monitors may report a high amount of time spent handling Deferred Procedure Calls (DPCs)."
"As explained by this [LWN article](https://lwn.net/Articles/790464/), split locks occur when an atomic instruction accesses memory that spans two cache lines, for example because of a misaligned memory access. To ensure that the instruction sees consistent data, the processor core acquires a global bus …
=> slit-lock dtc based on atomic misaligned ops // tpm dtc for virtual arm cpus

docs/documentation.md, src/vmaware.hpp
`[*]` Improved RDTSC patch detections 
`[*]` Made hyper-x debug messages clearer
`[/]` Fixed detection for QEMU's Hyper-V enlightenments
`[/]` Fixed **possible** false flag when probing VMware's Virtual Machine Communication Interface
`[/]` Fixed **possible** false flag when attempting to detect Hyper-V's VMBUS
=> 2.5.0-prerelease patches

src/cli.cpp
`[*]` Improved RDTSC patch detections 
`[*]` Made hyper-x debug messages clearer
`[/]` Fixed detection for QEMU's Hyper-V enlightenments
`[/]` Fixed **possible** false flag when probing VMware's Virtual Machine Communication Interface
`[/]` Fixed **possible** false flag when attempting to detect Hyper-V's VMBUS
=> 2.5.0-prerelease patches 
